coverage_service: cobertura_xml
scheme: testapp
xcodeproj: Example/AndesUI.xcodeproj
workspace: AndesUI.xcworkspace
source_directory: LibraryComponents
output_directory: coverage
ignore:
 - ../**/*/Xcode*
 - Example/*
 - Pods/*
