version: 2.1

parameters:
  type:
    type: enum
    enum: ["ci", "build", "default"]
    default: "default"
  build_context:
    type: string
    default: ""

# Default workflow will run on all branches except releases
default-workflow: &defaultWorkflow
  filters:
    branches:
      ignore:
        - master
        - /release\/.*$/
        - /v\/.*$/

orbs:
  meli: mercadolibre/ios@dev:publiclib

workflows:
  ci:
    jobs:
      - meli/test:
          <<: *defaultWorkflow
          build_context: << pipeline.parameters.build_context >>
          pipeline_id: << pipeline.id >>
          pipeline_number: << pipeline.number >>
      - meli/lint:
          <<: *defaultWorkflow
          build_context: << pipeline.parameters.build_context >>
          pipeline_id: << pipeline.id >>
          pipeline_number: << pipeline.number >>
  build:
    when:
      equal: [build, << pipeline.parameters.type >>]
    jobs:
      - meli/build-public:
          build_context: << pipeline.parameters.build_context >>
          pipeline_id: << pipeline.id >>
          pipeline_number: << pipeline.number >>
