version: 2.1

parameters:
  type:
    type: enum
    enum: ["ci", "build", "default"]
    default: "default"
  build_context:
    type: string
    default: ""

orbs:
  meli: mercadolibre/ios@volatile

workflows:
  ci:
    when:
      equal: [ci, << pipeline.parameters.type >>]
    jobs:
      - meli/test:
          build_context: << pipeline.parameters.build_context >>
          pipeline_id: << pipeline.id >>
          pipeline_number: << pipeline.number >>
      - meli/lint:
          build_context: << pipeline.parameters.build_context >>
          pipeline_id: << pipeline.id >>
          pipeline_number: << pipeline.number >>
          no_output_timeout: 30m
  build:
    when:
      equal: [build, << pipeline.parameters.type >>]
    jobs:
      - meli/build:
          build_context: << pipeline.parameters.build_context >>
          pipeline_id: << pipeline.id >>
          pipeline_number: << pipeline.number >>