version: 2.1

parameters:
  type:
    type: enum
    enum: ["ci", "build", "default"]
    default: "default"
  build_context:
    type: string
    default: ""

orbs:
  meli: mercadolibre/ios@dev:public

jobs:
  run-mds:
    <<: *defaultJob
    steps:
      # Checkout to our repo and add the ssh keys for doing git stuff
      - checkout
      - add_ssh_keys
      - run:
          name: Run MDS demoapp
          command: ./scripts/run_mds.sh


workflows:
  ci:
    when:
      equal: [ci, << pipeline.parameters.type >>]
    jobs:
      - meli/test:
          build_context: << pipeline.parameters.build_context >>
          pipeline_id: << pipeline.id >>
          pipeline_number: << pipeline.number >>
      - meli/lint:
          build_context: << pipeline.parameters.build_context >>
          pipeline_id: << pipeline.id >>
          pipeline_number: << pipeline.number >>
  build:
    when:
      equal: [build, << pipeline.parameters.type >>]
    jobs:
      - meli/build-public:
          build_context: << pipeline.parameters.build_context >>
          pipeline_id: << pipeline.id >>
          pipeline_number: << pipeline.number >>
      - run-mds:
          requires:
            - meli/build-public
